from datetime import datetime, timezone

FLIGHTS = [
    {
        "id": "FL001",
        "flight_number": "EK203",
        "airline": "Emirates",
        "aircraft_type": "A380",
        "aircraft_size": "F",
        "origin": "LHR",
        "destination": "DXB",
        "terminal": "T1",
        "assigned_stand": "A1-01",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T06:30:00Z",
        "estimated_time": "2025-01-15T06:25:00Z",
        "block_time_start": "2025-01-15T06:30:00Z",
        "block_time_end": "2025-01-15T08:45:00Z",
        "status": "on_time",
        "pax_count": 489,
    },
    {
        "id": "FL002",
        "flight_number": "QR501",
        "airline": "Qatar Airways",
        "aircraft_type": "B777-300ER",
        "aircraft_size": "E",
        "origin": "DOH",
        "destination": "DXB",
        "terminal": "T1",
        "assigned_stand": "A1-01",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T10:15:00Z",
        "estimated_time": "2025-01-15T10:40:00Z",
        "block_time_start": "2025-01-15T10:15:00Z",
        "block_time_end": "2025-01-15T12:30:00Z",
        "status": "delayed",
        "pax_count": 356,
    },
    {
        "id": "FL003",
        "flight_number": "BA107",
        "airline": "British Airways",
        "aircraft_type": "B787-9",
        "aircraft_size": "E",
        "origin": "LHR",
        "destination": "DXB",
        "terminal": "T1",
        "assigned_stand": "A1-02",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T07:00:00Z",
        "estimated_time": "2025-01-15T07:00:00Z",
        "block_time_start": "2025-01-15T07:00:00Z",
        "block_time_end": "2025-01-15T09:15:00Z",
        "status": "on_time",
        "pax_count": 264,
    },
    {
        "id": "FL004",
        "flight_number": "LH752",
        "airline": "Lufthansa",
        "aircraft_type": "A340-600",
        "aircraft_size": "E",
        "origin": "FRA",
        "destination": "DXB",
        "terminal": "T1",
        "assigned_stand": "A1-02",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T11:30:00Z",
        "estimated_time": "2025-01-15T11:30:00Z",
        "block_time_start": "2025-01-15T11:30:00Z",
        "block_time_end": "2025-01-15T14:00:00Z",
        "status": "on_time",
        "pax_count": 291,
    },
    {
        "id": "FL005",
        "flight_number": "SQ321",
        "airline": "Singapore Airlines",
        "aircraft_type": "A350-900",
        "aircraft_size": "E",
        "origin": "SIN",
        "destination": "DXB",
        "terminal": "T1",
        "assigned_stand": "A1-03",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T08:45:00Z",
        "estimated_time": "2025-01-15T08:50:00Z",
        "block_time_start": "2025-01-15T08:45:00Z",
        "block_time_end": "2025-01-15T11:00:00Z",
        "status": "on_time",
        "pax_count": 303,
    },
    {
        "id": "FL006",
        "flight_number": "EK512",
        "airline": "Emirates",
        "aircraft_type": "B777-300ER",
        "aircraft_size": "E",
        "origin": "DXB",
        "destination": "JFK",
        "terminal": "T1",
        "assigned_stand": "A1-03",
        "operation": "departure",
        "scheduled_time": "2025-01-15T13:00:00Z",
        "estimated_time": "2025-01-15T13:00:00Z",
        "block_time_start": "2025-01-15T11:30:00Z",
        "block_time_end": "2025-01-15T13:00:00Z",
        "status": "on_time",
        "pax_count": 396,
    },
    {
        "id": "FL007",
        "flight_number": "QF001",
        "airline": "Qantas",
        "aircraft_type": "A380",
        "aircraft_size": "F",
        "origin": "SYD",
        "destination": "DXB",
        "terminal": "T2",
        "assigned_stand": "B1-01",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T05:30:00Z",
        "estimated_time": "2025-01-15T05:20:00Z",
        "block_time_start": "2025-01-15T05:30:00Z",
        "block_time_end": "2025-01-15T08:00:00Z",
        "status": "early",
        "pax_count": 450,
    },
    {
        "id": "FL008",
        "flight_number": "CX888",
        "airline": "Cathay Pacific",
        "aircraft_type": "A350-1000",
        "aircraft_size": "E",
        "origin": "HKG",
        "destination": "DXB",
        "terminal": "T2",
        "assigned_stand": "B1-01",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T10:00:00Z",
        "estimated_time": "2025-01-15T09:50:00Z",
        "block_time_start": "2025-01-15T10:00:00Z",
        "block_time_end": "2025-01-15T12:30:00Z",
        "status": "early",
        "pax_count": 334,
    },
    {
        "id": "FL009",
        "flight_number": "JL043",
        "airline": "Japan Airlines",
        "aircraft_type": "B787-9",
        "aircraft_size": "E",
        "origin": "NRT",
        "destination": "DXB",
        "terminal": "T2",
        "assigned_stand": "B1-02",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T14:30:00Z",
        "estimated_time": "2025-01-15T14:30:00Z",
        "block_time_start": "2025-01-15T14:30:00Z",
        "block_time_end": "2025-01-15T16:45:00Z",
        "status": "on_time",
        "pax_count": 186,
    },
    {
        "id": "FL010",
        "flight_number": "AF218",
        "airline": "Air France",
        "aircraft_type": "A330-200",
        "aircraft_size": "D",
        "origin": "CDG",
        "destination": "DXB",
        "terminal": "T2",
        "assigned_stand": "B1-03",
        "operation": "arrival",
        "scheduled_time": "2025-01-15T16:00:00Z",
        "estimated_time": "2025-01-15T16:15:00Z",
        "block_time_start": "2025-01-15T16:00:00Z",
        "block_time_end": "2025-01-15T18:30:00Z",
        "status": "delayed",
        "pax_count": 224,
    },
]

STANDS = [
    {
        "id": "A1-01",
        "terminal": "T1",
        "type": "contact",
        "has_plb": True,
        "max_aircraft_size": "F",
        "associated_gate": "G01",
        "position": {"x": 100, "y": 50},
    },
    {
        "id": "A1-02",
        "terminal": "T1",
        "type": "contact",
        "has_plb": True,
        "max_aircraft_size": "E",
        "associated_gate": "G02",
        "position": {"x": 100, "y": 120},
    },
    {
        "id": "A1-03",
        "terminal": "T1",
        "type": "contact",
        "has_plb": True,
        "max_aircraft_size": "E",
        "associated_gate": "G03",
        "position": {"x": 100, "y": 190},
    },
    {
        "id": "A1-04",
        "terminal": "T1",
        "type": "contact",
        "has_plb": True,
        "max_aircraft_size": "D",
        "associated_gate": "G04",
        "position": {"x": 100, "y": 260},
    },
    {
        "id": "A1-05",
        "terminal": "T1",
        "type": "remote",
        "has_plb": False,
        "max_aircraft_size": "E",
        "associated_gate": None,
        "position": {"x": 100, "y": 330},
    },
    {
        "id": "B1-01",
        "terminal": "T2",
        "type": "contact",
        "has_plb": True,
        "max_aircraft_size": "F",
        "associated_gate": "G05",
        "position": {"x": 400, "y": 50},
    },
    {
        "id": "B1-02",
        "terminal": "T2",
        "type": "contact",
        "has_plb": True,
        "max_aircraft_size": "E",
        "associated_gate": "G06",
        "position": {"x": 400, "y": 120},
    },
    {
        "id": "B1-03",
        "terminal": "T2",
        "type": "contact",
        "has_plb": False,
        "max_aircraft_size": "D",
        "associated_gate": "G07",
        "position": {"x": 400, "y": 190},
    },
    {
        "id": "B1-04",
        "terminal": "T2",
        "type": "remote",
        "has_plb": False,
        "max_aircraft_size": "F",
        "associated_gate": None,
        "position": {"x": 400, "y": 260},
    },
    {
        "id": "B1-05",
        "terminal": "T2",
        "type": "remote",
        "has_plb": False,
        "max_aircraft_size": "D",
        "associated_gate": None,
        "position": {"x": 400, "y": 330},
    },
]

# Aircraft size ordering for compatibility checks
AIRCRAFT_SIZE_ORDER = ["A", "B", "C", "D", "E", "F"]

GATES = [
    {"id": "G01", "terminal": "T1", "type": "contact", "is_plb": True, "connected_stands": ["A1-01"]},
    {"id": "G02", "terminal": "T1", "type": "contact", "is_plb": True, "connected_stands": ["A1-02"]},
    {"id": "G03", "terminal": "T1", "type": "contact", "is_plb": True, "connected_stands": ["A1-03"]},
    {"id": "G04", "terminal": "T1", "type": "contact", "is_plb": True, "connected_stands": ["A1-04"]},
    {"id": "G05", "terminal": "T2", "type": "contact", "is_plb": True, "connected_stands": ["B1-01"]},
    {"id": "G06", "terminal": "T2", "type": "contact", "is_plb": True, "connected_stands": ["B1-02"]},
    {"id": "G07", "terminal": "T2", "type": "non_contact", "is_plb": False, "connected_stands": ["B1-03"]},
]

GRAPH_EDGES = {
    "plb_connections": [
        {"stand": "A1-01", "gate": "G01", "type": "plb"},
        {"stand": "A1-02", "gate": "G02", "type": "plb"},
        {"stand": "A1-03", "gate": "G03", "type": "plb"},
        {"stand": "A1-04", "gate": "G04", "type": "plb"},
        {"stand": "B1-01", "gate": "G05", "type": "plb"},
        {"stand": "B1-02", "gate": "G06", "type": "plb"},
    ],
    "walking_connections": [
        {"stand": "A1-04", "gate": "G03", "type": "walking", "distance_meters": 85},
        {"stand": "B1-03", "gate": "G07", "type": "walking", "distance_meters": 120},
        {"stand": "B1-04", "gate": "G07", "type": "bus", "distance_meters": 450},
        {"stand": "B1-05", "gate": "G07", "type": "bus", "distance_meters": 520},
    ],
    "adjacency_constraints": [
        {"stand_a": "A1-01", "stand_b": "A1-02", "type": "wingtip", "min_clearance_meters": 7.5},
        {"stand_a": "A1-03", "stand_b": "A1-04", "type": "wingtip", "min_clearance_meters": 7.5},
        {"stand_a": "B1-01", "stand_b": "B1-02", "type": "adjacency", "min_clearance_meters": 5.0},
    ],
}

DASHBOARD_METRICS = {
    "on_time_performance": {"current": 78, "previous": 82, "unit": "%"},
    "stand_utilization": {"occupied": 7, "total": 10, "unit": "stands"},
    "upcoming_arrivals_2h": {"total": 4, "on_time": 3, "delayed": 1},
    "plb_usage": {"current": 71, "target": 85, "unit": "%"},
}

CHAT_HISTORY = {
    "messages": [
        {
            "id": "msg-1",
            "role": "user",
            "content": "What's the current stand utilization for Terminal 1?",
            "timestamp": "2025-01-15T08:05:00Z",
        },
        {
            "id": "msg-2",
            "role": "tool",
            "tool_name": "fetch_stand_status",
            "status": "complete",
            "duration": "0.3s",
            "content": "T1: 4/5 stands occupied (80%). A1-05 available (remote).",
            "timestamp": "2025-01-15T08:05:01Z",
        },
        {
            "id": "msg-3",
            "role": "assistant",
            "content": "Terminal 1 currently has 4 out of 5 stands occupied — that's 80% utilization. The only available stand is A1-05 (remote stand, no PLB). All contact stands with PLB are currently in use.",
            "timestamp": "2025-01-15T08:05:02Z",
        },
        {
            "id": "msg-4",
            "role": "user",
            "content": "QR501 is showing delayed. Can it still go to A1-01?",
            "timestamp": "2025-01-15T08:20:00Z",
        },
        {
            "id": "msg-5",
            "role": "tool",
            "tool_name": "check_assignment_feasibility",
            "status": "complete",
            "duration": "0.6s",
            "content": "QR501 ETA revised to 10:40. A1-01 clear from 08:45. B777-300ER compatible with stand (size E ≤ F).",
            "timestamp": "2025-01-15T08:20:01Z",
        },
        {
            "id": "msg-6",
            "role": "assistant",
            "content": "Yes, QR501 can still use A1-01. Even with the 25-minute delay (revised ETA 10:40), there's a comfortable 1h 55min buffer after EK203 departs at 08:45. The B777-300ER is size category E, which fits within A1-01's maximum size F capacity.",
            "timestamp": "2025-01-15T08:20:02Z",
        },
    ],
    "suggested_prompts": [
        "Show me all delayed flights",
        "What's the current stand utilization?",
        "Which flights arrive in the next hour?",
        "Reassign EK512 to a PLB stand",
        "Show T1 capacity forecast",
    ],
}
